apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: widgets.example.com  # Define a unique name for your CRD
spec:
  group: example.com  # Define the API group
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                size:
                  type: string
  scope: Namespaced  # Can be "Namespaced" or "Cluster"
  names:
    plural: widgets
    singular: widget
    kind: Widget
    shortNames:
      - wd
#once the CRD is defined, you can create a custom resource (CR) using the new Widget object:
apiVersion: example.com/v1
kind: Widget
metadata:
  name: my-widget
spec:
  size: "large"
