apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-storage
provisioner: kubernetes.io/aws-ebs  # Change based on cloud provider
parameters:
  type: gp2  # AWS EBS type (for example)
  fsType: ext4
allowVolumeExpansion: true
reclaimPolicy: Retain
